import 'server-only';

import { resolveAgent, type AgentResolution } from './identity/agent-book';
import { formatTwinDataForPrompt } from './prompts/ai-twin-prompts';
import { PaidCallError, internalUrl, paidPost } from './x402/pay-client';

/**
 * Twin-to-twin screening date.
 *
 * Two people's AI twins hold a short conversation and produce a compatibility
 * report *before* the humans are introduced. It exists because the expensive,
 * unpleasant part of online dating is discovering incompatibility after
 * several days of messaging — and because a twin can ask the blunt questions
 * a person would not open with.
 *
 * Three properties make it more than a chatbot demo:
 *
 *   Both sides are provably human. Each twin's agent must resolve through
 *   AgentBook to a verified human before a single token is generated.
 *   Every turn is paid. Each twin's turn is an x402-settled HBAR payment
 *   against the metered inference endpoint, so the conversation has a real,
 *   visible cost and cannot be run at scale by a spammer.
 *   Every payment is auditable. Each turn's receipt lands on an HCS topic.
 *
 * The alternating structure is an A2A-style negotiation: two autonomous
 * agents exchanging positions and settling payment per exchange, rather than
 * one model roleplaying both halves of a dialogue.
 */

export interface ScreeningTurn {
  index: number;
  /** Which twin spoke. */
  speaker: 'A' | 'B';
  agentId: string;
  twinName: string;
  text: string;
  priceHbar: string | null;
  paymentStatus: string;
  receipt: {
    sequenceNumber: string | null;
    transactionId: string | null;
    hashscanUrl: string | null;
    onChain: boolean;
  } | null;
  /** False when the text came from the local sandbox rather than a model. */
  live: boolean;
}

export interface ScreeningReport {
  sessionId: string;
  compatibilityScore: number;
  sharedInterests: string[];
  frictionPoints: string[];
  summary: string;
  transcript: ScreeningTurn[];
  totalCostHbar: string;
  hcsMessageIds: string[];
  topicUrl: string | null;
  agents: {
    a: { agentId: string; humanBacked: boolean; source: string; twinName: string };
    b: { agentId: string; humanBacked: boolean; source: string; twinName: string };
  };
  /** Whether every turn was generated by a real model. */
  live: boolean;
  /** Threshold the score must clear before human chat unlocks. */
  unlockThreshold: number;
  unlocked: boolean;
}

export class ScreeningError extends Error {
  readonly code: string;

  constructor(message: string, code: string) {
    super(message);
    this.name = 'ScreeningError';
    this.code = code;
  }
}

/** Score a pair must reach before direct human chat opens. */
export const UNLOCK_THRESHOLD = Number.parseInt(process.env.SCREENING_UNLOCK_THRESHOLD || '55', 10);

/** Output cap per conversational turn. Keeps turns short and priced sanely. */
const TURN_MAX_TOKENS = 320;
const REPORT_MAX_TOKENS = 900;

function personaSystemPrompt(twin: any, counterpartName: string): string {
  return [
    `You are the AI twin of ${twin?.name || 'someone'}, speaking on their behalf on a dating platform.`,
    '',
    formatTwinDataForPrompt(twin ?? {}),
    '',
    `You are on a short screening call with ${counterpartName}'s AI twin. Your job is to work out`,
    'whether the two humans are actually compatible — not to sell your person or to be agreeable.',
    '',
    'Rules:',
    `- Speak as ${twin?.name || 'your person'} would: same voice, same values, same dealbreakers.`,
    '- Two or three sentences per turn. This is a conversation, not a monologue.',
    '- Ask about things that would genuinely matter to your person, including the awkward ones.',
    '- Be honest about friction. A screening that hides an incompatibility has failed at its job.',
    '- Never invent facts about your person that are not in the profile above.',
  ].join('\n');
}

function reportSystemPrompt(): string {
  return [
    'You are a compatibility analyst reviewing a screening conversation between two people\'s AI twins.',
    '',
    'Return strict JSON only, no prose and no code fences, with exactly these keys:',
    '{',
    '  "compatibilityScore": <integer 0-100>,',
    '  "sharedInterests": [<short strings>],',
    '  "frictionPoints": [<short strings>],',
    '  "summary": "<two or three sentences addressed to both people>"',
    '}',
    '',
    'Be discriminating. A score above 80 should be rare and mean genuine alignment on values and',
    'life direction, not merely a pleasant exchange. Name real friction where it appeared —',
    'a report that flatters both parties is worthless to them.',
  ].join('\n');
}

interface TurnResponse {
  text?: string;
  live?: boolean;
  payment?: { priceHbar?: string; settled?: boolean; unmetered?: boolean };
  receipt?: {
    sequenceNumber?: string | null;
    transactionId?: string | null;
    hashscanUrl?: string | null;
    topicUrl?: string | null;
    onChain?: boolean;
  };
}

/**
 * Runs a screening conversation and produces a report.
 *
 * Both agents are resolved first and the whole thing aborts before any paid
 * call if either is not human-backed — otherwise a fake twin could spend a
 * real user's HBAR just by being invited to a screening.
 */
export async function runScreeningDate(params: {
  agentIdA: string;
  agentIdB: string;
  twinA: any;
  twinB: any;
  turns?: number;
  sessionId?: string;
}): Promise<ScreeningReport> {
  const turns = Math.max(2, Math.min(params.turns ?? 4, 8));
  const sessionId = params.sessionId || `scr_${Date.now().toString(36)}`;

  /* ---------- Eligibility, before spending anything ---------- */
  const [agentA, agentB] = await Promise.all([
    resolveAgent(params.agentIdA),
    resolveAgent(params.agentIdB),
  ]);

  assertHumanBacked(agentA, 'A');
  assertHumanBacked(agentB, 'B');

  if (params.agentIdA.toLowerCase() === params.agentIdB.toLowerCase()) {
    throw new ScreeningError('A twin cannot screen itself', 'SAME_AGENT');
  }

  const nameA = params.twinA?.name || agentA.twinName || 'Twin A';
  const nameB = params.twinB?.name || agentB.twinName || 'Twin B';

  const systemA = personaSystemPrompt(params.twinA, nameB);
  const systemB = personaSystemPrompt(params.twinB, nameA);

  /* ---------- Alternating paid turns ---------- */
  const transcript: ScreeningTurn[] = [];
  let totalCost = 0;
  let allLive = true;

  for (let index = 0; index < turns; index += 1) {
    const isA = index % 2 === 0;
    const speaker: 'A' | 'B' = isA ? 'A' : 'B';
    const agentId = isA ? params.agentIdA : params.agentIdB;

    const prompt =
      transcript.length === 0
        ? `Open the screening call with ${nameB}'s twin. Introduce your person briefly and ask your first real question.`
        : [
            'Screening conversation so far:',
            '',
            transcript
              .map((turn) => `${turn.twinName}'s twin: ${turn.text}`)
              .join('\n\n'),
            '',
            'Reply with your next turn only.',
          ].join('\n');

    const result = await payForTurn({
      agentId,
      prompt,
      system: isA ? systemA : systemB,
      maxTokens: TURN_MAX_TOKENS,
      sessionId,
    });

    const price = Number.parseFloat(result.payment?.priceHbar ?? '0');
    if (Number.isFinite(price)) totalCost += price;
    if (!result.live) allLive = false;

    transcript.push({
      index,
      speaker,
      agentId,
      twinName: isA ? nameA : nameB,
      text: result.text ?? '',
      priceHbar: result.payment?.priceHbar ?? null,
      paymentStatus: result.payment?.unmetered
        ? 'unmetered'
        : result.payment?.settled
          ? 'settled'
          : 'unknown',
      receipt: result.receipt
        ? {
            sequenceNumber: result.receipt.sequenceNumber ?? null,
            transactionId: result.receipt.transactionId ?? null,
            hashscanUrl: result.receipt.hashscanUrl ?? null,
            onChain: Boolean(result.receipt.onChain),
          }
        : null,
      live: Boolean(result.live),
    });
  }

  /* ---------- The analysis, also a paid call ---------- */
  const analysis = await payForTurn({
    // Billed to A's agent: the initiator pays for the report on the
    // conversation they requested.
    agentId: params.agentIdA,
    system: reportSystemPrompt(),
    prompt: [
      `Screening conversation between ${nameA}'s twin and ${nameB}'s twin:`,
      '',
      transcript.map((turn) => `${turn.twinName}'s twin: ${turn.text}`).join('\n\n'),
      '',
      'Produce the compatibility JSON.',
    ].join('\n'),
    maxTokens: REPORT_MAX_TOKENS,
    effort: 'high',
    sessionId,
  });

  const analysisPrice = Number.parseFloat(analysis.payment?.priceHbar ?? '0');
  if (Number.isFinite(analysisPrice)) totalCost += analysisPrice;

  const parsed = parseAnalysis(analysis.text ?? '', transcript, params);
  const score = parsed.compatibilityScore;

  const hcsMessageIds = [...transcript, { receipt: analysis.receipt } as any]
    .map((turn: any) => turn.receipt?.sequenceNumber)
    .filter((id: string | null | undefined): id is string => Boolean(id));

  return {
    sessionId,
    compatibilityScore: score,
    sharedInterests: parsed.sharedInterests,
    frictionPoints: parsed.frictionPoints,
    summary: parsed.summary,
    transcript,
    totalCostHbar: Number.parseFloat(totalCost.toFixed(8)).toString(),
    hcsMessageIds,
    topicUrl: analysis.receipt?.topicUrl ?? transcript[0]?.receipt?.hashscanUrl ?? null,
    agents: {
      a: {
        agentId: agentA.agentId,
        humanBacked: agentA.humanBacked,
        source: agentA.source,
        twinName: nameA,
      },
      b: {
        agentId: agentB.agentId,
        humanBacked: agentB.humanBacked,
        source: agentB.source,
        twinName: nameB,
      },
    },
    live: allLive && Boolean(analysis.live),
    unlockThreshold: UNLOCK_THRESHOLD,
    unlocked: score >= UNLOCK_THRESHOLD,
  };
}

function assertHumanBacked(agent: AgentResolution, side: 'A' | 'B'): void {
  if (agent.humanBacked) return;

  throw new ScreeningError(
    agent.source === 'unknown'
      ? `Twin ${side} is not registered as an agent`
      : `Twin ${side} does not resolve to a verified human`,
    'AGENT_NOT_HUMAN_BACKED',
  );
}

async function payForTurn(params: {
  agentId: string;
  prompt: string;
  system: string;
  maxTokens: number;
  effort?: 'low' | 'medium' | 'high' | 'xhigh' | 'max';
  sessionId: string;
}): Promise<TurnResponse> {
  try {
    const { body } = await paidPost<TurnResponse>(internalUrl('/api/twin/infer'), {
      prompt: params.prompt,
      system: params.system,
      maxTokens: params.maxTokens,
      effort: params.effort ?? 'low',
      agentId: params.agentId,
      sessionId: params.sessionId,
    });
    return body;
  } catch (error) {
    if (error instanceof PaidCallError) {
      throw new ScreeningError(
        `A screening turn could not be paid for (HTTP ${error.status})`,
        'PAYMENT_FAILED',
      );
    }
    throw error;
  }
}

/**
 * Parses the analysis JSON, tolerating a model that wraps it in prose.
 *
 * Falls back to a score derived from declared-interest overlap rather than
 * throwing: the user has already paid for the conversation, so a malformed
 * final response should still yield a usable report.
 */
function parseAnalysis(
  raw: string,
  transcript: ScreeningTurn[],
  params: { twinA: any; twinB: any },
): {
  compatibilityScore: number;
  sharedInterests: string[];
  frictionPoints: string[];
  summary: string;
} {
  const jsonMatch = raw.match(/\{[\s\S]*\}/);

  if (jsonMatch) {
    try {
      const parsed = JSON.parse(jsonMatch[0]);
      const score = Number(parsed.compatibilityScore);

      if (Number.isFinite(score)) {
        return {
          compatibilityScore: Math.max(0, Math.min(100, Math.round(score))),
          sharedInterests: toStringArray(parsed.sharedInterests),
          frictionPoints: toStringArray(parsed.frictionPoints),
          summary: typeof parsed.summary === 'string' ? parsed.summary : '',
        };
      }
    } catch {
      /* fall through to the heuristic */
    }
  }

  const shared = overlap(params.twinA?.interests, params.twinB?.interests);

  return {
    compatibilityScore: Math.min(100, 40 + shared.length * 8),
    sharedInterests: shared,
    frictionPoints: [],
    summary:
      transcript.length > 0
        ? 'The twins held a full conversation, but the compatibility analysis could not be parsed. The transcript below is complete.'
        : 'No conversation took place.',
  };
}

function toStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.filter((item): item is string => typeof item === 'string').slice(0, 8);
}

function overlap(a: unknown, b: unknown): string[] {
  if (!Array.isArray(a) || !Array.isArray(b)) return [];
  const right = new Set(b.map((item) => String(item).toLowerCase()));
  return a
    .filter((item) => right.has(String(item).toLowerCase()))
    .map((item) => String(item))
    .slice(0, 8);
}
